import type { NextPage } from "next";
import Head from "next/head";
import { Countries, Header } from "../components";
import { useState } from "react";
import { useDarkMode } from "usehooks-ts";

const Home: NextPage = () => {
  const { isDarkMode } = useDarkMode();
  const [input, setInput] = useState<string>("");
  const [selectedRegion, setSelectedRegion] = useState<string>("");
  return (
    <>
      <Head>
        <title>REST Countries API</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header
        input={input}
        setInput={setInput}
        isDarkMode={isDarkMode}
        selectedRegion={selectedRegion}
        setSelectedRegion={setSelectedRegion}
      />
      <main
        className={`${
          !isDarkMode ? "bg-[#202c37]" : "bg-[#fafafa]"
        } main pb-12`}
      >
        <Countries input={input} region={selectedRegion} />
      </main>
    </>
  );
};

export default Home;
