import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/Navbar";
import Countries from "./Countries";
import { useState } from "react";

const Home: NextPage = () => {
  const [toggleTheme, setToggleTheme] = useState<boolean>(false);
  return (
    <>
      <Head>
        <title>REST Countries API</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar toggleTheme={toggleTheme} setToggleTheme={setToggleTheme} />
      <main
        className={`${toggleTheme ? "bg-[#202c37]" : "bg-[#fafafa]"} h-[100%]`}
      >
        <Countries toggleTheme={toggleTheme} />
      </main>
    </>
  );
};

export default Home;
